
# Server
server.port=8080
spring.application.name=nba-stats-api

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/nba_stats
spring.datasource.username=postgres
spring.datasource.password=0228366023abc

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# balldontlie API
balldontlie.api.base-url=https://api.balldontlie.io/v1
balldontlie.api.key=eb0de0d3-9379-4ff7-b81e-95a7ab53a17d
