POST http://localhost:8080/api/teams/sync


###
POST http://localhost:8080/api/players/sync?cursor=1

###
GET http://localhost:8080/api/teams

###
GET http://localhost:8080/api/players

###
GET http://localhost:8080/api/players/999999

###
GET http://localhost:8080/api/players/search?name=LeBron

###
GET http://localhost:8080/api/players/search?name=James

###
POST http://localhost:8080/api/games/sync?cursor=18447018

###
GET http://localhost:8080/api/games/today

###
GET http://localhost:8080/api/games?date=2026-04-1

###
GET http://localhost:8080/api/teams/3/record

###
GET http://localhost:8080/api/teams/standings

###
GET http://localhost:8080/api/games/recent/2 ? limit=20




